# Change these first
owner: Gerche # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Celta
    url: https://celta.be
  - name: Sels
    url: https://sels.be
  - name: Flyinggroup
    url: https://www.flyinggroup.aero
  - name: Salkaperu
    url: https://salkaperu.be
  - name: Vissaversa
    url: https://vissaversa.com
  - name: Momocollective
    url: https://momocollective.be
  - name: Boon
    url: https://boon.be
  - name: Horal
    url: https://horal.be
  - name: Floordenil
    url: https://floordenil.com
assignees:
  - Gerche

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "The **Celta** webservices monitor powered by GitHub."
  introMessage: This is an open-source uptime monitor and status page, which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
